version: "3.8"

services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

    volumes:
    - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql